version: '3.9'
services:
  web:
    image: fuadadio/cloudbox:${TAG}
    command: ./wait-for-it.sh postgres:5432 -- ./docker-entrypoint.sh
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - mongo
    restart: on-failure
    volumes:
      - .:/app
  
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=cloudbox
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - pgdata:/var/lib/postgresql/data
  
  mongo:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data

  celery:
    build: .
    command: celery -A cloudbox.celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - C_FORCE_ROOT=true
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    restart: always
    network_mode: host

volumes:
  pgdata:
  mongodata:
  redisdata:
