"""added a created at field to Transaction table

Revision ID: 2170a4074fd2
Revises: f0ea9257839f
Create Date: 2022-08-08 15:56:19.201252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2170a4074fd2'
down_revision = 'f0ea9257839f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'created_at')
    # ### end Alembic commands ###
