"""empty message

Revision ID: 580015ccb7b9
Revises: 42eaf2a767a5
Create Date: 2022-07-21 10:04:44.773585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '580015ccb7b9'
down_revision = '42eaf2a767a5'
branch_labels = None
depends_on = None


subscription_plan_enum = postgresql.ENUM('free', 'basic', 'standard', 'premium', name='subscription_plan_enum', create_type=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_plan_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('subscription_plan', subscription_plan_enum, nullable=False, server_default= "free"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_plan')
    subscription_plan_enum.drop(op.get_bind())
    # ### end Alembic commands ###
