"""added amount to transaction model

Revision ID: f0ea9257839f
Revises: 2c23f46dc948
Create Date: 2022-08-07 01:18:50.773728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ea9257839f'
down_revision = '2c23f46dc948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'amount')
    # ### end Alembic commands ###
