name: Deploy CloudBox to DockerHub then pull to EC2

on:
  push:
    tags:
      - '**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        run: echo "$AWS_PRIVATE_KEY"
      - name: Deploy in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo cd /home/ubuntu/CloudBox && 
            docker-compose down &&
            git pull &&
            docker-compose up -d --build
