name: Deploy CloudBox to DockerHub then pull to EC2

on:
  push:
    tags:
      - '**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}		
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" >> key.cer && chmod 600 key.cer
          ssh -o StrictHostKeyChecking=no -i key.cer ${USER_NAME}@${HOSTNAME}
          sudo cd /home/ubuntu/CloudBox && 
          sudo docker-compose down &&
          sudo git pull &&
          sudo docker-compose up -d --build
